/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface;
import core.Bluetooth;
import core.Resources;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.bluetooth.BluetoothStateException;
import javax.bluetooth.RemoteDevice;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import support.Log;
import support.Logs;
import support.User;
import support.Users;
/**
 *
 * @author adichouhanofficial
 */
public class AddingUser extends javax.swing.JFrame {

    /**
     * Creates new form AddingUser
     */
    private static List<RemoteDevice> client ;
    private  DefaultListModel<String>model;
    private Map<Integer,RemoteDevice> mapper;
    Bluetooth bluetooth ;
    private boolean isPaired;
    AdminPanel adminPanel=null;

     private void clearEverything()
    {
        model.clear();
        client.clear();
        mapper.clear();
        Bname.setText("---Select Device---");
        Baddress.setText("---Select Device---");
        pairstatus.setText("---Select Device---");
    }
    private void search()
    {  
        
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        try 
        {
            bluetooth = new Bluetooth();
            client=bluetooth.searchDevices();
        } 
        catch (BluetoothStateException ex) 
        {
            JOptionPane.showMessageDialog(this,"Please turn on the bluetooth first !!!");
            dispose();
        } 
        catch (InterruptedException ex) 
        {
            
        }
        int i=0;
        mylist.setModel(model);
        for(RemoteDevice x: client)
        {
            
            try
            {
                model.addElement(x.getFriendlyName(false));
            }
            catch(IOException e)
            {
                model.addElement(x.getBluetoothAddress());
            }
            finally
            {
                mapper.put(i, x);
                i++;
            }
        }
        searching.setText("Search Completed! Choose device");
        this.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
//        refresh.setVisible(true);
    }
    public AddingUser() 
    {
        initComponents();
        Heading.setText("Add Admin");
        admin.setSelected(true);
        refresh.setVisible(false);
        Image image = Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png"));
        setIconImage(image);
        
    }
    public AddingUser(AdminPanel adminPanel)
    {
        initComponents();
        refresh.setVisible(false);    
        this.adminPanel=adminPanel;
        Image image = Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png"));
        setIconImage(image);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usergroup = new javax.swing.ButtonGroup();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Heading = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        ListHeader = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mylist = new javax.swing.JList<>();
        searching = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        usertype = new javax.swing.JLabel();
        admin = new javax.swing.JRadioButton();
        naive = new javax.swing.JRadioButton();
        pairstatus = new javax.swing.JLabel();
        Bname = new javax.swing.JLabel();
        pairedButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        Baddress = new javax.swing.JLabel();
        refresh = new javax.swing.JLabel();

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add User");
        setIconImages(null);
        setLocation(new java.awt.Point(700, 300));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowDeactivated(java.awt.event.WindowEvent evt) {
                formWindowDeactivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add-user.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 70, 70));

        Heading.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        Heading.setText("ADD USER");
        jPanel1.add(Heading, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 10, 230, -1));

        jSeparator2.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator2.setForeground(new java.awt.Color(153, 153, 153));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 530, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 524, 80));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        ListHeader.setText("Available Devices");

        mylist.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        mylist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mylistMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(mylist);

        searching.setText("Searching for nearby Devices....");
        searching.setAutoscrolls(true);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Device Name : ");
        jLabel5.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Device Address :");
        jLabel6.setEnabled(false);

        usertype.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        usertype.setText("User Type : ");
        usertype.setEnabled(false);

        admin.setBackground(new java.awt.Color(255, 255, 255));
        usergroup.add(admin);
        admin.setText("Admin");
        admin.setEnabled(false);
        admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminActionPerformed(evt);
            }
        });

        naive.setBackground(new java.awt.Color(255, 255, 255));
        usergroup.add(naive);
        naive.setSelected(true);
        naive.setText("Naive");
        naive.setEnabled(false);
        naive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                naiveActionPerformed(evt);
            }
        });

        pairstatus.setText("---Select Device---");
        pairstatus.setEnabled(false);

        Bname.setBackground(new java.awt.Color(0, 153, 204));
        Bname.setText("---Select Device---");
        Bname.setEnabled(false);

        pairedButton.setText("Pair Device");
        pairedButton.setEnabled(false);
        pairedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pairedButtonActionPerformed(evt);
            }
        });

        addButton.setText("Add User");
        addButton.setEnabled(false);
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator1.setForeground(new java.awt.Color(153, 153, 153));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Paired : ");
        jLabel4.setEnabled(false);

        Baddress.setText("---Select Device---");
        Baddress.setEnabled(false);

        refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/refreshButton.png"))); // NOI18N
        refresh.setLabelFor(refresh);
        refresh.setToolTipText("Refresh");
        refresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                refreshMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(refresh))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(ListHeader))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(usertype)
                                    .addComponent(addButton))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Baddress, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pairstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(admin)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(naive))
                                    .addComponent(pairedButton)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(Bname, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(searching, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(ListHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(searching, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Bname, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(Baddress, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(pairstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(usertype, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(admin, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(naive, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addButton)
                            .addComponent(pairedButton))))
                .addGap(312, 312, 312)
                .addComponent(refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 524, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        searching.setText("Searching for nearby Devices....");
        search();       
        //searching.setText("Search Completed! Choose device");
        if(adminPanel!=null)
        {
            usertype.setEnabled(true);
            admin.setEnabled(true);
            naive.setEnabled(true);
        }
        
//        refresh.setVisible(true);       
    }//GEN-LAST:event_formWindowOpened

    private void naiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_naiveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_naiveActionPerformed

    private void adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminActionPerformed

    private void mylistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mylistMouseClicked
        // TODO add your handling code here:
        
        if(mylist.getSelectedValue()!=null)
        {
            try 
            {
                RemoteDevice device=mapper.get(mylist.getSelectedIndex());
                String Dname=device.getFriendlyName(false);
                String address = Resources.getFormattedAddress(device.getBluetoothAddress());
                isPaired=device.isTrustedDevice();
                Bname.setText(Dname);
                Baddress.setText(address);
                pairstatus.setText(isPaired?"Yes":"No");
                pairedButton.setEnabled(!isPaired);
                addButton.setEnabled(isPaired);
                
            } 
            catch (IOException ex)
            {
            }
        }
    }//GEN-LAST:event_mylistMouseClicked

    private void pairedButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pairedButtonActionPerformed
        // TODO add your handling code here:
        {
            
            RemoteDevice device = mapper.get(mylist.getSelectedIndex());
            isPaired=Bluetooth.pairing(device);
            if(isPaired) 
            {
                JOptionPane.showMessageDialog(this,"Device successfully paired");
                pairedButton.setEnabled(false);
                addButton.setEnabled(true);
            }
        }
    }//GEN-LAST:event_pairedButtonActionPerformed

    private void refreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshMouseClicked
        // TODO add your handling code here:  
//        refresh.setVisible(false);
//        searching.setText("Searching for nearby Devices....");
//        clearEverything();
//        search();
    }//GEN-LAST:event_refreshMouseClicked

    private void refreshMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshMousePressed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_refreshMousePressed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        User user = new User(Bname.getText(),Baddress.getText(),admin.isSelected());
        try
        {
            Users.addUser(user);
            if(adminPanel==null)
            {
                Log log = new Log("root","Admin added : "+user.getName());
                Logs.addLog(log);
                JOptionPane.showMessageDialog(this,"Admin Successfully added ! Restart the app");
                System.exit(0);   // suggest : if any problem arises then use dispose instead of exit
            }      
            else
            {
                String type=user.isType()?"Admin":"Naive user";
                Log log = new Log(adminPanel.getUser().getName(),type+" added : "+user.getName());
                Logs.addLog(log);
                JOptionPane.showMessageDialog(this,"New "+type+" Successfully added !");
                this.adminPanel.setVisible(true);
                dispose();
            }
        } 
        catch (IOException ex) 
        {
            JOptionPane.showMessageDialog(this,"Something bad happened !!! ");  
            if(adminPanel!=null)
            {
                dispose();
                this.adminPanel.setVisible(true);
            }      
        }
        
    }//GEN-LAST:event_addButtonActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        if(adminPanel!=null)
            adminPanel.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void formWindowDeactivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowDeactivated
        // TODO add your handling code here:
        client.clear();
        model.clear();
        mapper.clear();
    }//GEN-LAST:event_formWindowDeactivated

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        client  = new ArrayList();
        model=new <String>DefaultListModel();
        mapper =new HashMap();
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) 
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddingUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddingUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddingUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddingUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddingUser().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Baddress;
    private javax.swing.JLabel Bname;
    private javax.swing.JLabel Heading;
    private javax.swing.JLabel ListHeader;
    private javax.swing.JButton addButton;
    private javax.swing.JRadioButton admin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JList<String> mylist;
    private javax.swing.JRadioButton naive;
    private javax.swing.JButton pairedButton;
    private javax.swing.JLabel pairstatus;
    private javax.swing.JLabel refresh;
    private javax.swing.JLabel searching;
    private javax.swing.ButtonGroup usergroup;
    private javax.swing.JLabel usertype;
    // End of variables declaration//GEN-END:variables
}
