/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import core.Bluetooth;
import core.Resources;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.bluetooth.BluetoothStateException;
import javax.bluetooth.RemoteDevice;
import javax.microedition.io.Connector;
import javax.obex.ClientSession;
import javax.obex.HeaderSet;
import javax.obex.ResponseCodes;
import javax.swing.JOptionPane;
import support.Log;
import support.Logs;
import support.User;
import support.Users;

/**
 *
 * @author adichouhanofficial
 */
public class AdminLogin extends javax.swing.JFrame {
    
    private Bluetooth bt;
    private List<RemoteDevice> devices;
    private RemoteDevice device;
    private List<User> users;
    private User user;
    boolean bterror=false;
    /**
     * Creates new form AdminLogin
     */
    public AdminLogin() 
    {
        initComponents();
        device=null;
        user=null;
        try 
        {
            bt = new Bluetooth();
            devices=bt.searchDevices();  
            users=Users.getUsers();
        }catch (BluetoothStateException ex)
        {        
            JOptionPane.showMessageDialog(this,"Please turn on the bluetooth first !!!");
            bterror=true;
            
        } catch (InterruptedException ex) 
        {
//            ex.printStackTrace();
        } catch (IOException ex) 
        {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this,"Something went wrong !!!");
            bterror=true;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        VerifyButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        close = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(725, 275));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(247, 250, 189));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/man.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 39, -1, -1));

        username.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        jPanel2.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 327, 256, 33));

        VerifyButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        VerifyButton.setText("Verify Bluetooth Device");
        VerifyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerifyButtonActionPerformed(evt);
            }
        });
        jPanel2.add(VerifyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 373, 256, 40));

        jLabel2.setText("Enter Username:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 308, -1, -1));

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/error.png"))); // NOI18N
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        jPanel2.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void VerifyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerifyButtonActionPerformed
        // TODO add your handling code here:
        String uname = username.getText();
        String address=null;
        for(RemoteDevice device : devices)
        {
            try 
            {    //use method which tell you connection instead or pair status(istrusted)
                if((device.getFriendlyName(false)).equalsIgnoreCase(uname)  && device.isTrustedDevice())
                {
                        this.device=device;
                        break;
                } 
            } 
            catch (IOException ex) 
            {
                JOptionPane.showMessageDialog(this,"Connection Failed !");
                dispose();
                bterror=true;
            }
        }
        if(!bterror)
        {
            try {
                String URL =  bt.getServerURL(device);
                Resources.connection = (ClientSession) Connector.open(URL);
                HeaderSet hsConnectReply = Resources.connection.connect(null);
                if (hsConnectReply.getResponseCode() != ResponseCodes.OBEX_HTTP_OK)
                {
                    System.out.println("Failed to connect");
                    JOptionPane.showMessageDialog(this,"Failed To Connect to Device !");
                }
                else{
                    if(device!=null)
                    {
                        address=Resources.getFormattedAddress(device.getBluetoothAddress());

                        for(User user: users)
                        {
                            if(address.equals(user.getMAC()) && user.isType())
                            {
                                this.user=user;
                                break;
                            }
                        }  
                        if(user==null)
                        {
                            JOptionPane.showMessageDialog(this,"You are not Authorized user !!!");
                            dispose();
                        }
                        else
                        {
                            //                    if(!uname.equals(user.getName()))
                            //                    {
                            //                        // update bluetooth name it has been changed
                            //                    }
                            
                            Log log = new Log(user.getName(),"Admin logged in...");
                            try
                            {
                                Logs.addLog(log);
                            } catch (IOException ex) {
                                JOptionPane.showMessageDialog(this,"Something went worng with file system !!!");
                                dispose();
                            }
                            new AdminPanel(device,user).setVisible(true); 
                            dispose();
                            
                        }
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(this,"Please make sure that your device bluetooth is descoverable !");
                        username.setText("");
                    }
                }
            } catch (IOException ex) {
                Logger.getLogger(AdminLogin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_VerifyButtonActionPerformed

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_closeMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        if(bterror)
            dispose();
    }//GEN-LAST:event_formWindowActivated

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminLogin().setVisible(true);
            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton VerifyButton;
    private javax.swing.JLabel close;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
