/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import core.EncryptionEngine;
import core.Resources;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import javax.bluetooth.RemoteDevice;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import support.FileStatus;
import support.Log;
import support.Logs;
import support.User;
import support.UserFile;
import support.UserFiles;

/**
 *
 * @author adichouhanofficial
 */
public class AdminPanel extends javax.swing.JFrame {
    private static RemoteDevice admin;
    private static User user;
    boolean connection;

    /**
     * Creates new form AdminPanel
     */
//    public AdminPanel() 
//    {
////        initComponents();
//        System.err.print("Unauthosrized access denied");
//    }
     public AdminPanel(RemoteDevice admin,User user) 
    {
        initComponents();
        this.admin=admin;
        this.user=user;
        jLabel1.setText("Welcome to Desksure "+user.getName());
        Image image = Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png"));
        setIconImage(image);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        ManageUserButton = new javax.swing.JLabel();
        LockButton = new javax.swing.JLabel();
        AddUserButton = new javax.swing.JLabel();
        ManageFileButton = new javax.swing.JLabel();
        LogButton = new javax.swing.JLabel();
        AddFileButton = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Admin Panel");
        setLocation(new java.awt.Point(700, 250));
        addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                formPropertyChange(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setText("Welcome to Desksure admin");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 0, 350, 64));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/admin.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 0, -1, 80));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ManageUserButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/MANAGE.png"))); // NOI18N
        ManageUserButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ManageUserButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ManageUserButtonMouseClicked(evt);
            }
        });
        jPanel2.add(ManageUserButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(325, 40, 80, -1));

        LockButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/unlocked.png"))); // NOI18N
        LockButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LockButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LockButtonMouseClicked(evt);
            }
        });
        jPanel2.add(LockButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        AddUserButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add-user.png"))); // NOI18N
        AddUserButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AddUserButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddUserButtonMouseClicked(evt);
            }
        });
        jPanel2.add(AddUserButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 40, 80, -1));

        ManageFileButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/manage-file.png"))); // NOI18N
        ManageFileButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ManageFileButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ManageFileButtonMouseClicked(evt);
            }
        });
        jPanel2.add(ManageFileButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 154, 75, -1));

        LogButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/log-file-format.png"))); // NOI18N
        LogButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LogButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogButtonMouseClicked(evt);
            }
        });
        jPanel2.add(LogButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(326, 154, 70, -1));

        AddFileButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/file.png"))); // NOI18N
        AddFileButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AddFileButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddFileButtonMouseClicked(evt);
            }
        });
        jPanel2.add(AddFileButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 154, -1, -1));

        jLabel9.setText("Manage Protection");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 111, 140, -1));

        jLabel10.setText("Add User");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 110, 80, -1));

        jLabel11.setText("Manage User");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 111, 100, -1));

        jLabel12.setText("View User Log");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 225, 100, -1));

        jLabel13.setText("Manage Files");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 225, 90, -1));

        jLabel14.setText("Add File");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 225, 64, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 71, 440, 265));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                .addGap(3, 3, 3))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LockButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LockButtonMouseClicked
        // TODO add your handling code here:
        if(Resources.lockFlag) // true mean active state
        {
            int confirm=JOptionPane.showConfirmDialog(this,"Do you really want to remove bluetooth protection ?","Confirm",1);
            if(confirm==0)
            {
                try {
                    ImageIcon icon = new ImageIcon(getClass().getResource("/icons/locked_1.png"));
                    Log log = new Log(user.getName(),"Desksure Turned off !!!");
                    Logs.addLog(log);
                    LockButton.setIcon(icon);
                    Resources.lockFlag=false;
                } catch (IOException ex) 
                {
                    JOptionPane.showMessageDialog(this,"Something went wrong with file system");
                }
            }
        }
        else
        {
            int confirm=JOptionPane.showConfirmDialog(this,"Do you really want to add bluetooth protection again ?","Confirm",1);
            if(confirm==0)
            {
                try 
                {
                    ImageIcon icon = new ImageIcon(getClass().getResource("/icons/unlocked.png"));
                    Log log = new Log(user.getName(),"Desksure Turned on !!!");
                    Logs.addLog(log);
                    LockButton.setIcon(icon);
                    Resources.lockFlag=true;
                } catch (IOException ex) {
                   JOptionPane.showMessageDialog(this,"Something went wrong with file system");
                }
            }
        }
    }//GEN-LAST:event_LockButtonMouseClicked

    private void AddUserButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddUserButtonMouseClicked
        // TODO add your handling code here:
        new AddingUser(this).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_AddUserButtonMouseClicked

    private void ManageUserButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageUserButtonMouseClicked
        // TODO add your handling code here:
       new ManageUsers(this).setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_ManageUserButtonMouseClicked

    private void AddFileButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddFileButtonMouseClicked
        // TODO add your handling code here:
    if(Resources.lockFlag)
    {    
        JFileChooser chooser= new JFileChooser("D:\\");
        chooser.setMultiSelectionEnabled(false);
        if(chooser.showDialog(this,"Choose a file")==JFileChooser.APPROVE_OPTION)
        {
            File file=chooser.getSelectedFile();
            String extension = Resources.fetchFileExtension(file.getAbsolutePath());
            if(file.exists()&& file.isFile())
            {
                if(!extension.equals("desksure"))
                {    
                    int confirm=JOptionPane.showConfirmDialog(this,"Do you really want to Secure this File using DeskSure ?");
                    if(confirm==0) // if user click on yes
                    {
                        String key = Resources.key(user.getMAC());  //generating key by Formatted MAC address
                        try
                        {
                            EncryptionEngine ee = new EncryptionEngine(key);                            
                            UserFile userfile = new UserFile(file,extension,user,FileStatus.ENCRYPTED);
                            UserFiles.addFile(userfile);
                            Log log = new Log(user.getName(),"New File added : "+userfile.getFile().getName());
                            Logs.addLog(log);
                            ee.fileEncrypt(file);
                            file.setWritable(false);
                        } 
                        catch (IOException ex) 
                        { 
                            JOptionPane.showMessageDialog(this,"Something went wrong with file system");
                        }

                    }
                }
                else
                {
                    JOptionPane.showMessageDialog(this,"File is already secured by desksure !");
                }
            }        
        }
    }
    else
    {
        JOptionPane.showMessageDialog(this,"Application under Maintainance");
    }
    }//GEN-LAST:event_AddFileButtonMouseClicked

    private void formPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_formPropertyChange

    }//GEN-LAST:event_formPropertyChange

    private void ManageFileButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageFileButtonMouseClicked
        // TODO add your handling code here:
        new ManageFiles(this).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ManageFileButtonMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
      //  jLabel1.setText(user.getMAC());
    }//GEN-LAST:event_jLabel4MouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        admin=null; user=null;
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        Log log = new Log(user.getName(),"Admin logged out !!!");
        try 
        {
            Logs.addLog(log);
        } catch (IOException ex) 
        {
            JOptionPane.showMessageDialog(this,"Something went wrong with file system");
        }
    }//GEN-LAST:event_formWindowClosing

    private void LogButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogButtonMouseClicked
        // TODO add your handling code here:
        new LogDetails(this).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_LogButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPanel(admin,user).setVisible(true);
            }
        });
    }

    public RemoteDevice getAdmin(){return this.admin;}
    public User getUser(){return this.user;}
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddFileButton;
    private javax.swing.JLabel AddUserButton;
    private javax.swing.JLabel LockButton;
    private javax.swing.JLabel LogButton;
    private javax.swing.JLabel ManageFileButton;
    private javax.swing.JLabel ManageUserButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
