/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import javafx.scene.Cursor;

/**
 *
 * @author adichouhanofficial
 */
public class NewInstall extends javax.swing.JFrame {
    /**
     * Creates new form NewInstall
     */
    public NewInstall() {
        initComponents();
        start.setVisible(false);
        startbutton.setVisible(false);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        Welcometodesksure = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        start = new javax.swing.JLabel();
        startbutton = new javax.swing.JLabel();
        progress = new javax.swing.JProgressBar();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        knowmore = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Welcome to Desksure");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(102, 102, 102));
        setLocation(new java.awt.Point(600, 300));
        setUndecorated(true);
        setOpacity(0.9F);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(250, 241, 177));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/antivirus.png"))); // NOI18N
        jPanel2.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 240, 270));

        Welcometodesksure.setFont(new java.awt.Font("Sitka Text", 1, 36)); // NOI18N
        Welcometodesksure.setForeground(new java.awt.Color(255, 0, 0));
        Welcometodesksure.setText("Welcome to Desksure");
        jPanel2.add(Welcometodesksure, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 397, 50));

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/error.png"))); // NOI18N
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                closeMousePressed(evt);
            }
        });
        jPanel2.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Simple | Secure | User Friendly");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, -1, -1));

        start.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        start.setText("Lets Go");
        jPanel2.add(start, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 90, -1));

        startbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/right-arrow.png"))); // NOI18N
        startbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startbuttonMouseClicked(evt);
            }
        });
        jPanel2.add(startbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, 70, 70));

        progress.setBackground(new java.awt.Color(204, 204, 204));
        progress.setForeground(new java.awt.Color(0, 216, 92));
        progress.setToolTipText("Installing");
        progress.setBorderPainted(false);
        progress.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        progress.setFocusTraversalPolicyProvider(true);
        progress.setNextFocusableComponent(startbutton);
        progress.setOpaque(true);
        progress.setStringPainted(true);
        jPanel2.add(progress, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 700, 15));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 310));

        jPanel1.setBackground(new java.awt.Color(250, 241, 177));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel4.setText("Meet DeskSure.  Your personal File Protection Assistant !");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel5.setForeground(new java.awt.Color(51, 51, 255));
        jLabel5.setText("Desksure lets you protect your file while you are not around by keep them encrypted ! Uses your phone's bluetooth");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel6.setForeground(new java.awt.Color(51, 51, 255));
        jLabel6.setText("to ensure your presence, and only allows you to access your protected files.");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 10));

        knowmore.setBackground(new java.awt.Color(204, 204, 204));
        knowmore.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 13)); // NOI18N
        knowmore.setText("Know More");
        knowmore.setBorder(null);
        knowmore.setBorderPainted(false);
        knowmore.setContentAreaFilled(false);
        knowmore.setDebugGraphicsOptions(javax.swing.DebugGraphics.FLASH_OPTION);
        knowmore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                knowmoreActionPerformed(evt);
            }
        });
        jPanel1.add(knowmore, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, 100, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 700, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void knowmoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_knowmoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_knowmoreActionPerformed

    private void closeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMousePressed
       System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_closeMousePressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        new Loading().start();
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void startbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startbuttonMouseClicked
        // TODO add your handling code here:
        new AddingUser().setVisible(true);
        dispose();
    }//GEN-LAST:event_startbuttonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewInstall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewInstall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewInstall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewInstall.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewInstall().setVisible(true);
               
            }
            
        });
    }
    
class Loading extends Thread
{
    public void run() 
    {
        
        for(int i=20;i<101;i++)
        {
            progress.setValue(i);
            progress.setString(i+"%");
            try
            {
              if(i>97)
                Thread.sleep(500);
              else if(i>90)
                  Thread.sleep(200);
              else
                Thread.sleep(50);
            }
            catch(Exception e){}
            
        }
        progress.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        progress.setToolTipText("Installed");
        start.setVisible(true);
        startbutton.setVisible(true);    
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Welcometodesksure;
    private javax.swing.JLabel close;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton knowmore;
    private javax.swing.JLabel logo;
    private javax.swing.JProgressBar progress;
    private javax.swing.JLabel start;
    private javax.swing.JLabel startbutton;
    // End of variables declaration//GEN-END:variables
}
